import type { FormSection } from "@/components/client/forms/enhanced-dynamic-form"

// Personal Information Form for Individuals
export const personalInformationForm: FormSection[] = [
  {
    id: "basic-info",
    title: "Basic Information",
    description: "Please provide your basic personal information",
    fields: [
      {
        id: "title",
        type: "select",
        label: "Title",
        required: true,
        options: [
          { label: "Mr.", value: "mr" },
          { label: "Mrs.", value: "mrs" },
          { label: "Ms.", value: "ms" },
          { label: "Dr.", value: "dr" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "firstName",
        type: "text",
        label: "First Name",
        placeholder: "Enter your first name",
        required: true,
        validation: {
          minLength: 2,
          maxLength: 50,
        },
      },
      {
        id: "middleName",
        type: "text",
        label: "Middle Name",
        placeholder: "Enter your middle name (if applicable)",
        required: false,
      },
      {
        id: "lastName",
        type: "text",
        label: "Last Name",
        placeholder: "Enter your last name",
        required: true,
        validation: {
          minLength: 2,
          maxLength: 50,
        },
      },
      {
        id: "dateOfBirth",
        type: "date",
        label: "Date of Birth",
        required: true,
        regulatoryRequirement: true,
        helpText: "Your date of birth is required for identity verification and regulatory purposes.",
      },
      {
        id: "placeOfBirth",
        type: "text",
        label: "Place of Birth",
        placeholder: "City, Country",
        required: true,
        regulatoryRequirement: true,
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "nationality-info",
    title: "Nationality & Tax Information",
    description: "Please provide information about your nationality and tax residency",
    fields: [
      {
        id: "nationality",
        type: "country",
        label: "Primary Nationality",
        required: true,
        options: [
          { label: "United States", value: "us" },
          { label: "United Kingdom", value: "uk" },
          { label: "Canada", value: "ca" },
          { label: "Australia", value: "au" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "additionalNationalities",
        type: "multi-select",
        label: "Additional Nationalities",
        required: false,
        options: [
          { label: "United States", value: "us" },
          { label: "United Kingdom", value: "uk" },
          { label: "Canada", value: "ca" },
          { label: "Australia", value: "au" },
          { label: "Other", value: "other" },
        ],
        helpText: "Please select all countries where you hold citizenship",
      },
      {
        id: "taxResidency",
        type: "country",
        label: "Primary Tax Residency",
        required: true,
        options: [
          { label: "United States", value: "us" },
          { label: "United Kingdom", value: "uk" },
          { label: "Canada", value: "ca" },
          { label: "Australia", value: "au" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "taxIdentificationNumber",
        type: "text",
        label: "Tax Identification Number",
        placeholder: "Enter your tax ID number",
        required: true,
        regulatoryRequirement: true,
        helpText: "For US citizens, this is your Social Security Number (SSN)",
      },
      {
        id: "additionalTaxResidencies",
        type: "multi-select",
        label: "Additional Tax Residencies",
        required: false,
        options: [
          { label: "United States", value: "us" },
          { label: "United Kingdom", value: "uk" },
          { label: "Canada", value: "ca" },
          { label: "Australia", value: "au" },
          { label: "Other", value: "other" },
        ],
        helpText: "Please select all countries where you are a tax resident",
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "contact-info",
    title: "Contact Information",
    description: "How can we reach you?",
    fields: [
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email address",
        required: true,
      },
      {
        id: "phoneNumber",
        type: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
        validation: {
          pattern: "^[+]?[(]?[0-9]{3}[)]?[-\\s.]?[0-9]{3}[-\\s.]?[0-9]{4,6}$",
          patternMessage: "Please enter a valid phone number",
        },
      },
      {
        id: "alternativePhone",
        type: "phone",
        label: "Alternative Phone Number",
        placeholder: "Enter an alternative phone number (optional)",
        required: false,
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "address-info",
    title: "Residential Address",
    description: "Where do you currently live?",
    fields: [
      {
        id: "residentialAddress",
        type: "address",
        label: "Residential Address",
        required: true,
        regulatoryRequirement: true,
      },
      {
        id: "residenceDuration",
        type: "select",
        label: "How long have you lived at this address?",
        required: true,
        options: [
          { label: "Less than 1 year", value: "less_than_1" },
          { label: "1-3 years", value: "1_to_3" },
          { label: "3-5 years", value: "3_to_5" },
          { label: "5+ years", value: "more_than_5" },
        ],
      },
      {
        id: "previousAddressRequired",
        type: "checkbox",
        label: "Previous Address Required",
        placeholder: "I have lived at my current address for less than 3 years",
        required: false,
      },
      {
        id: "previousAddress",
        type: "address",
        label: "Previous Address",
        required: true,
        dependsOn: {
          field: "previousAddressRequired",
          value: true,
        },
      },
      {
        id: "mailingAddressSame",
        type: "checkbox",
        label: "Mailing Address",
        placeholder: "My mailing address is the same as my residential address",
        required: false,
      },
      {
        id: "mailingAddress",
        type: "address",
        label: "Mailing Address",
        required: true,
        dependsOn: {
          field: "mailingAddressSame",
          value: false,
        },
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "identification-info",
    title: "Identification Documents",
    description: "Please provide your identification information",
    fields: [
      {
        id: "idType",
        type: "select",
        label: "Primary ID Type",
        required: true,
        options: [
          { label: "Passport", value: "passport" },
          { label: "National ID Card", value: "national_id" },
          { label: "Driver's License", value: "drivers_license" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "idNumber",
        type: "text",
        label: "ID Number",
        placeholder: "Enter your ID number",
        required: true,
        regulatoryRequirement: true,
      },
      {
        id: "idIssueDate",
        type: "date",
        label: "Issue Date",
        required: true,
      },
      {
        id: "idExpiryDate",
        type: "date",
        label: "Expiry Date",
        required: true,
      },
      {
        id: "idIssuingCountry",
        type: "country",
        label: "Issuing Country",
        required: true,
        options: [
          { label: "United States", value: "us" },
          { label: "United Kingdom", value: "uk" },
          { label: "Canada", value: "ca" },
          { label: "Australia", value: "au" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "idDocument",
        type: "file-upload",
        label: "Upload ID Document",
        required: true,
        description: "Please upload a clear, color copy of your ID document",
        regulatoryRequirement: true,
      },
    ],
    entityTypes: ["individual"],
  },
]

// Financial Information Form for Individuals
export const financialInformationForm: FormSection[] = [
  {
    id: "employment-info",
    title: "Employment Information",
    description: "Please provide details about your current employment",
    fields: [
      {
        id: "employmentStatus",
        type: "select",
        label: "Employment Status",
        required: true,
        options: [
          { label: "Employed", value: "employed" },
          { label: "Self-Employed", value: "self-employed" },
          { label: "Unemployed", value: "unemployed" },
          { label: "Retired", value: "retired" },
          { label: "Student", value: "student" },
        ],
      },
      {
        id: "occupation",
        type: "text",
        label: "Occupation",
        placeholder: "Enter your job title",
        required: true,
        dependsOn: {
          field: "employmentStatus",
          value: "employed",
        },
      },
      {
        id: "employerName",
        type: "text",
        label: "Employer Name",
        placeholder: "Enter your employer's name",
        required: true,
        dependsOn: {
          field: "employmentStatus",
          value: "employed",
        },
      },
      {
        id: "employerAddress",
        type: "address",
        label: "Employer Address",
        required: true,
        dependsOn: {
          field: "employmentStatus",
          value: "employed",
        },
      },
      {
        id: "businessName",
        type: "text",
        label: "Business Name",
        placeholder: "Enter your business name",
        required: true,
        dependsOn: {
          field: "employmentStatus",
          value: "self-employed",
        },
      },
      {
        id: "businessAddress",
        type: "address",
        label: "Business Address",
        required: true,
        dependsOn: {
          field: "employmentStatus",
          value: "self-employed",
        },
      },
      {
        id: "industryType",
        type: "select",
        label: "Industry",
        required: true,
        options: [
          { label: "Finance & Banking", value: "finance" },
          { label: "Technology", value: "technology" },
          { label: "Healthcare", value: "healthcare" },
          { label: "Education", value: "education" },
          { label: "Retail", value: "retail" },
          { label: "Manufacturing", value: "manufacturing" },
          { label: "Other", value: "other" },
        ],
        dependsOn: {
          field: "employmentStatus",
          value: "employed",
        },
      },
      {
        id: "yearsInCurrentEmployment",
        type: "select",
        label: "Years in Current Employment",
        required: true,
        options: [
          { label: "Less than 1 year", value: "less_than_1" },
          { label: "1-3 years", value: "1_to_3" },
          { label: "3-5 years", value: "3_to_5" },
          { label: "5-10 years", value: "5_to_10" },
          { label: "10+ years", value: "more_than_10" },
        ],
        dependsOn: {
          field: "employmentStatus",
          value: "employed",
        },
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "income-info",
    title: "Income Information",
    description: "Please provide details about your income",
    fields: [
      {
        id: "annualIncome",
        type: "select",
        label: "Annual Income",
        required: true,
        options: [
          { label: "Less than $25,000", value: "under_25k" },
          { label: "$25,000 - $49,999", value: "25k_50k" },
          { label: "$50,000 - $74,999", value: "50k_75k" },
          { label: "$75,000 - $99,999", value: "75k_100k" },
          { label: "$100,000 - $149,999", value: "100k_150k" },
          { label: "$150,000 - $249,999", value: "150k_250k" },
          { label: "$250,000 - $499,999", value: "250k_500k" },
          { label: "$500,000 - $999,999", value: "500k_1m" },
          { label: "$1,000,000 or more", value: "over_1m" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "incomeSource",
        type: "select",
        label: "Primary Source of Income",
        required: true,
        options: [
          { label: "Salary", value: "salary" },
          { label: "Business Income", value: "business" },
          { label: "Investments", value: "investments" },
          { label: "Inheritance", value: "inheritance" },
          { label: "Retirement", value: "retirement" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "otherIncomeSource",
        type: "text",
        label: "Please Specify Other Income Source",
        required: true,
        dependsOn: {
          field: "incomeSource",
          value: "other",
        },
      },
      {
        id: "additionalIncomeSources",
        type: "multi-select",
        label: "Additional Income Sources",
        required: false,
        options: [
          { label: "Salary", value: "salary" },
          { label: "Business Income", value: "business" },
          { label: "Investments", value: "investments" },
          { label: "Inheritance", value: "inheritance" },
          { label: "Retirement", value: "retirement" },
          { label: "Rental Income", value: "rental" },
          { label: "Royalties", value: "royalties" },
          { label: "Other", value: "other" },
        ],
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "wealth-source",
    title: "Source of Wealth",
    description: "Please provide information about the source of your wealth",
    fields: [
      {
        id: "wealthSource",
        type: "radio",
        label: "Primary Source of Wealth",
        required: true,
        options: [
          { label: "Employment Income", value: "employment" },
          { label: "Business Ownership", value: "business" },
          { label: "Investments", value: "investments" },
          { label: "Inheritance", value: "inheritance" },
          { label: "Sale of Property", value: "property" },
          { label: "Gift", value: "gift" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "wealthDescription",
        type: "textarea",
        label: "Please provide additional details about your source of wealth",
        placeholder: "Enter details here...",
        required: true,
        validation: {
          maxLength: 500,
        },
        regulatoryRequirement: true,
      },
      {
        id: "wealthDocumentation",
        type: "file-upload",
        label: "Source of Wealth Documentation",
        required: false,
        description:
          "Please upload documentation supporting your source of wealth (e.g., tax returns, investment statements)",
      },
      {
        id: "estimatedNetWorth",
        type: "select",
        label: "Estimated Net Worth",
        required: true,
        options: [
          { label: "Less than $100,000", value: "under_100k" },
          { label: "$100,000 - $250,000", value: "100k_250k" },
          { label: "$250,000 - $500,000", value: "250k_500k" },
          { label: "$500,000 - $1,000,000", value: "500k_1m" },
          { label: "$1,000,000 - $5,000,000", value: "1m_5m" },
          { label: "$5,000,000 - $10,000,000", value: "5m_10m" },
          { label: "$10,000,000 or more", value: "over_10m" },
        ],
        regulatoryRequirement: true,
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "financial-assets",
    title: "Financial Assets",
    description: "Please provide information about your financial assets",
    fields: [
      {
        id: "bankAccounts",
        type: "checkbox",
        label: "Bank Accounts",
        placeholder: "I have bank accounts",
        required: false,
      },
      {
        id: "investments",
        type: "checkbox",
        label: "Investments",
        placeholder: "I have investment accounts (stocks, bonds, etc.)",
        required: false,
      },
      {
        id: "realEstate",
        type: "checkbox",
        label: "Real Estate",
        placeholder: "I own real estate",
        required: false,
      },
      {
        id: "businessOwnership",
        type: "checkbox",
        label: "Business Ownership",
        placeholder: "I own or have significant ownership in businesses",
        required: false,
      },
      {
        id: "cryptoAssets",
        type: "checkbox",
        label: "Cryptocurrency",
        placeholder: "I own cryptocurrency or digital assets",
        required: false,
      },
      {
        id: "otherAssets",
        type: "textarea",
        label: "Other Significant Assets",
        placeholder: "Please describe any other significant assets you own",
        required: false,
      },
    ],
    entityTypes: ["individual"],
  },
]

// Political Exposure and Risk Assessment Form for Individuals
export const riskAssessmentForm: FormSection[] = [
  {
    id: "political-exposure",
    title: "Political Exposure",
    description: "Please provide information about any political exposure",
    fields: [
      {
        id: "politicallyExposed",
        type: "radio",
        label: "Are you a politically exposed person (PEP) or closely associated with one?",
        required: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
        regulatoryRequirement: true,
        helpText:
          "A politically exposed person is someone who holds a prominent public position, or is closely related to such a person.",
      },
      {
        id: "pepDetails",
        type: "textarea",
        label: "Please provide details about your political exposure",
        placeholder: "Enter details here...",
        required: true,
        dependsOn: {
          field: "politicallyExposed",
          value: "yes",
        },
        validation: {
          maxLength: 500,
        },
        regulatoryRequirement: true,
      },
      {
        id: "pepPosition",
        type: "select",
        label: "Position Held",
        required: true,
        dependsOn: {
          field: "politicallyExposed",
          value: "yes",
        },
        options: [
          { label: "Head of State/Government", value: "head_of_state" },
          { label: "Senior Politician", value: "politician" },
          { label: "Senior Government Official", value: "government_official" },
          { label: "Senior Judicial Official", value: "judicial_official" },
          { label: "Senior Military Official", value: "military_official" },
          { label: "Senior Executive of State-Owned Corporation", value: "state_executive" },
          { label: "Important Political Party Official", value: "party_official" },
          { label: "Family Member of PEP", value: "family_member" },
          { label: "Close Associate of PEP", value: "close_associate" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "pepCountry",
        type: "country",
        label: "Country of Political Exposure",
        required: true,
        dependsOn: {
          field: "politicallyExposed",
          value: "yes",
        },
        options: [
          { label: "United States", value: "us" },
          { label: "United Kingdom", value: "uk" },
          { label: "Canada", value: "ca" },
          { label: "Australia", value: "au" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "risk-profile",
    title: "Risk Profile Assessment",
    description: "Please answer the following questions to help us understand your risk profile",
    fields: [
      {
        id: "investmentExperience",
        type: "select",
        label: "Investment Experience",
        required: true,
        options: [
          { label: "None", value: "none" },
          { label: "Limited (1-3 years)", value: "limited" },
          { label: "Moderate (3-5 years)", value: "moderate" },
          { label: "Extensive (5+ years)", value: "extensive" },
        ],
      },
      {
        id: "riskTolerance",
        type: "radio",
        label: "Risk Tolerance",
        required: true,
        options: [
          { label: "Conservative - Prefer low risk investments", value: "conservative" },
          { label: "Moderate - Balance between risk and return", value: "moderate" },
          { label: "Aggressive - Willing to accept higher risk for higher returns", value: "aggressive" },
        ],
      },
      {
        id: "investmentHorizon",
        type: "select",
        label: "Investment Time Horizon",
        required: true,
        options: [
          { label: "Short-term (Less than 1 year)", value: "short" },
          { label: "Medium-term (1-5 years)", value: "medium" },
          { label: "Long-term (5+ years)", value: "long" },
        ],
      },
      {
        id: "financialGoals",
        type: "multi-select",
        label: "Financial Goals",
        required: true,
        options: [
          { label: "Capital Preservation", value: "preservation" },
          { label: "Income Generation", value: "income" },
          { label: "Capital Growth", value: "growth" },
          { label: "Retirement Planning", value: "retirement" },
          { label: "Education Funding", value: "education" },
          { label: "Estate Planning", value: "estate" },
          { label: "Tax Optimization", value: "tax" },
          { label: "Other", value: "other" },
        ],
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "transaction-profile",
    title: "Expected Transaction Profile",
    description: "Please provide information about your expected transaction activity",
    fields: [
      {
        id: "expectedTransactionFrequency",
        type: "select",
        label: "Expected Transaction Frequency",
        required: true,
        options: [
          { label: "Daily", value: "daily" },
          { label: "Weekly", value: "weekly" },
          { label: "Monthly", value: "monthly" },
          { label: "Quarterly", value: "quarterly" },
          { label: "Annually", value: "annually" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "expectedTransactionAmount",
        type: "select",
        label: "Expected Transaction Amount (Average)",
        required: true,
        options: [
          { label: "Less than $1,000", value: "under_1k" },
          { label: "$1,000 - $10,000", value: "1k_10k" },
          { label: "$10,000 - $50,000", value: "10k_50k" },
          { label: "$50,000 - $100,000", value: "50k_100k" },
          { label: "$100,000 - $500,000", value: "100k_500k" },
          { label: "More than $500,000", value: "over_500k" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "expectedCountries",
        type: "multi-select",
        label: "Countries you expect to send/receive funds to/from",
        required: true,
        options: [
          { label: "United States", value: "us" },
          { label: "United Kingdom", value: "uk" },
          { label: "European Union", value: "eu" },
          { label: "Canada", value: "ca" },
          { label: "Australia", value: "au" },
          { label: "Asia Pacific", value: "apac" },
          { label: "Middle East", value: "me" },
          { label: "Africa", value: "africa" },
          { label: "Latin America", value: "latam" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
      {
        id: "expectedTransactionPurpose",
        type: "multi-select",
        label: "Purpose of Expected Transactions",
        required: true,
        options: [
          { label: "Investment", value: "investment" },
          { label: "Savings", value: "savings" },
          { label: "Business Operations", value: "business" },
          { label: "Personal Expenses", value: "personal" },
          { label: "Real Estate Purchase", value: "real_estate" },
          { label: "Education", value: "education" },
          { label: "Other", value: "other" },
        ],
        regulatoryRequirement: true,
      },
    ],
    entityTypes: ["individual"],
  },
  {
    id: "sanctions-screening",
    title: "Sanctions Screening",
    description: "Please provide information for sanctions screening",
    fields: [
      {
        id: "sanctionsDeclaration",
        type: "checkbox",
        label: "Sanctions Declaration",
        placeholder:
          "I confirm that I am not subject to any sanctions, and I am not aware of any circumstances that would make me subject to sanctions",
        required: true,
        regulatoryRequirement: true,
      },
      {
        id: "highRiskCountryConnection",
        type: "radio",
        label: "Do you have connections to high-risk countries?",
        required: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
        regulatoryRequirement: true,
        helpText:
          "High-risk countries include those with significant deficiencies in anti-money laundering and counter-terrorism financing measures.",
      },
      {
        id: "highRiskCountryDetails",
        type: "textarea",
        label: "Please provide details about your connections to high-risk countries",
        placeholder: "Enter details here...",
        required: true,
        dependsOn: {
          field: "highRiskCountryConnection",
          value: "yes",
        },
        validation: {
          maxLength: 500,
        },
        regulatoryRequirement: true,
      },
    ],
    entityTypes: ["individual"],
  },
]
